### PR TITLE
Milestone 4: Set Up Controllers

### PR DESCRIPTION
**Pull request by topeogunleye**
## Milestone 4: Set Up Controllers

In this Pull Request, I:

- Added Routes for posts, users.
- Added PostsController and UsersController
- Added template for PostsController#index
- Added template for UsersController#index
- Added template for PostsController#show
- Added template for UsersController#show

Message To Reviewer of [Blog-app views and Blog-app conrollers specs. please mark request as invalid. I submitted the wrong pull request

### CODE REVIEW

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Temi,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
- Controllers and corresponding views & routes properly defined ❣️ 
- Good ReadMe ❣️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
- MIT license link in your ReadMe is broken, kindly endeavor to fix it.

Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @topeogunleye , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- Good commit history ✔️
- Good PR description ✔️
- Your README file is professional ✔️


## Required Changes ♻️
_Check the comments under the review._
- as required your test should include tests that ensure the correct view template is rendered. Example: `expect(response).to render_template(:show)`
- Spec file should include tests that ensure the response body includes the correct placeholder text. Example : `expect(response.body).to include("Welcome to user index page")` 👋🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @topeogunleye👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️

- [ ] I don't see you worked on any of the views, Please take a look at the project [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md) and make sure you implement all the project requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@thecodechaser, I submitted the wrong pull request for this activity. This pull request is meant for controllers.

**Comment by topeogunleye** [comment]
> Hi @topeogunleye ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
>  [ 68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f704d7a746a7a67774b58676c4d4d747348732f67697068792e676966 ](https://camo.githubusercontent.com/824bcf982f91c38a81f61241bfa3a829fc679376e65a49413613f1051ef255c3/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f704d7a746a7a67774b58676c4d4d747348732f67697068792e676966) [ ](https://camo.githubusercontent.com/824bcf982f91c38a81f61241bfa3a829fc679376e65a49413613f1051ef255c3/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f704d7a746a7a67774b58676c4d4d747348732f67697068792e676966)
> 
> ## Highlights
> * Good commit history ✔️
> * Good PR description ✔️
> * Your README file is professional ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * as required your test should include tests that ensure the correct view template is rendered. Example: `expect(response).to render_template(:show)`
> * Spec file should include tests that ensure the response body includes the correct placeholder text. Example : `expect(response.body).to include("Welcome to user index page")` 👋🏾
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@alexander16108, Can you please kindly mark the request as invalid. I submitted the wrong pull request as seen from the PR Description doesn't match the PR.

**Comment by alexander16108** [comment]
hi @topeogunleye I'm sorry I have already requested changes on your dashboard sorry for the mix-up

**Comment by topeogunleye** [comment]
> hi @topeogunleye I'm sorry I have already requested changes on your dashboard sorry for the mix-up

Okay, thank you

**Review by bimbolabuari — COMMENTED** [review]
Hello @topeogunleye  👋,

_This is an additional review as a result of the second opinion request._

- Having submitted multiple milestones using this PR, the last two reviews should have been invalidated reviews, therefore, you can disregard the reviews and we will work on invalidating the reviews.

Keep rocking 🚀!

**Pull request merged**
